name: zermelo
description: Zermelo Dart package
version: 0.0.4
homepage: https://github.com/netlob/zermelo.dart
repository: https://github.com/netlob/zermelo.dart
issue_tracker: https://github.com/netlob/zermelo.dart/issues
documentation: https://github.com/netlob/zermelo.dart

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  http: ^0.13.5
